config/routes.rb
Abstract::Application.routes.draw do
  resources :institutions, :authors
  devise_for :users
  
  resources :conferences do
    resources :submissions
  end
  
  resources :submissions do
    resources :authorships
    put 'submit', :on => :member
  end
  
  resources :users, :only => [:index, :show]
  
  root :to => "conferences#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  
  belongs_to :institution
  
  has_many :authorships
  has_many :submissions, :through => :authorships
  
  validates :full_name, :presence => true
  validates :email, :presence => true, :uniqueness => true, :email_format => true
  validates :institution_id, :presence => true
  
  def full_name
    [first_name, last_name].join(' ')
  end
  
  def full_name=(name)
    return false if name.nil?
    split = name.split(' ', 2)
    self.first_name = split.first
    self.last_name = split.last
  end
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :author
  belongs_to :submission
  
  validates :author_id, :submission_id, :presence => true
  
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :submissions
  belongs_to :poc, :class_name => "User"
  
  scope :upcoming, where("conferences.end_date > ?", Date.today)
  scope :past, where("conferences.end_date < ?", Date.today)
  scope :with_open_submissions, where("conferences.submission_deadline > ?", Time.now)
  
  validates :start_date, :end_date, :submission_deadline, :presence => true
  validates :name, :presence => true, :uniqueness => true
  
  def taking_submissions?
    Time.now < self.submission_deadline
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :users
  has_many :authors
  
  validates :name, :presence => true, :uniqueness => true
  
  attr_accessible :name

end

app/models/submission.rb
class Submission < ActiveRecord::Base

  belongs_to :user
  belongs_to :conference
  
  has_many :authorships
  has_many :authors, :through => :authorships
  
  has_attached_file :image, :storage => ENV['S3_BUCKET'] ? :s3 : :filesystem, 
                    :s3_credentials => {
                      :access_key_id => ENV['S3_KEY'],
                      :secret_access_key => ENV['S3_SECRET']
                    },
                    :bucket => ENV['S3_BUCKET'],
                    :path => "/:attachment/:id/:style/:filename", 
                    :styles => { :publishable => "500x500>" } 
  
  validates :title, :presence => true, :uniqueness => { :scope => :user_id }  
  validates :user_id, :presence => true
  validates :body, :presence => true
  validates_attachment_size :image, :less_than => 4.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  validates :state, :presence => true
      
  attr_accessible :title, :body, :image, :conference_id
  
  state_machine :initial => :awaiting_authors do
        
    event :author_added do
      transition :to => :pending_submission, :from => [:awaiting_authors]
    end

    event :submit do
      transition :to => :submitted, :from => [:pending_submission]
    end
    
    event :approve do
      transition :to => :approved, :from => [:submitted]
    end
    
    event :denied do
      transition :to => :denied, :from => [:submitted]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :submissions
  has_many :conferences, :foreign_key => "poc_id"
  belongs_to :institution
    
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :intitution_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < InheritedResources::Base
  before_filter :authenticate_user!
end

app/controllers/authors_controller.rb
class AuthorsController < AuthenticatedController
end

app/controllers/authorships_controller.rb
class AuthorshipsController < AuthenticatedController
  belongs_to :submission
  
  def create
    create! do |success, failure|
      success.html { 
        @submission.author_added! if @submission.authors.count == 1
        redirect_to submission_url(@submission) 
      }
    end
  end

end

app/controllers/conferences_controller.rb
class ConferencesController < AuthenticatedController
  
  def new
    @conference = current_user.conferences.build
  end
  
  def create
    @conference = current_user.conferences.build(params[:conference])
    create!
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < AuthenticatedController
end

app/controllers/submissions_controller.rb
class SubmissionsController < AuthenticatedController
#  belongs_to :conference, :optional => true

  def create
    @submission = current_user.submissions.build(params[:submission])
    create! { new_submission_authorship_url(@submission) }
  end
  
  def submit
    @submission = Submission.find(params[:id])
    @submission.submit!
    redirect_to @submission
  end

end

app/controllers/users_controller.rb
class UsersController < AuthenticatedController
  actions :index, :show
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
  
  def submission_deadline_distance(conference)
    return distance_of_time_in_words(Time.now, conference.submission_deadline) if 
      conference.taking_submissions?
    "No longer accepting submissions."
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<% title "Authors" %>

<table>
  <tr>
    <th>Author</th>
    <th>Email</th>
    <th>Institution</th>
  </tr>
  
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.full_name %></td>
      <td><%= author.email %></td>
      <td><%= author.institution.name %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Add a new author", new_author_url %>

app/views/authors/new.html.erb
<% title "New Author" %>

<%= form_for(@author) do |f| %>
  
  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.collection_select :institution_id, Institution.all, :id, :name, :prompt => "Select the author's institution." %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/show.html.erb
<% title @author.full_name %>

<h2>Contact Info</h2>
<table>
  <tr>
    <th>Email:</th>
    <td><%= @author.email %></td>
  </tr>
  <tr>
    <th>Institution:</th>
    <td><%= @author.institution.name %></td>
  </tr>
</table>

<h2>Submissions</h2>
<ul>
  <% @author.submissions.each do |sub| %>
    <li><%= link_to sub.title, sub_url %></li>
  <% end %>
</ul>

app/views/authorships/_form.html.erb
<%= form_for([@submission, @authorship]) do |f| %>
  <%= f.error_messages %>
  
  <div class="field">
    <%= f.collection_select :author_id, Author.all, :id, :full_name, :prompt => "Select an author." %>
  </div>
  
  <div class="actions">
    <%= f.submit "Add the author" %>
  </div>
  
<% end %>

app/views/authorships/new.html.erb
<% title 'Add an author' %>

<%= render 'form' %>

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <%= f.error_messages %>
  
  <div class="field">
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
  </div>
  
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>
  
  <div class="field">
    <%= f.label :submission_deadline %>
    <%= f.datetime_select :submission_deadline %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/conferences/edit.html.erb
<% title @conference.name %>

<%= render 'form' %>

app/views/conferences/index.html.erb
<% title "Conferences" %>


<p>
  <%= link_to "Add a new conference", new_conference_url %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Start</th>
    <th>End</th>
    <th>Submission Deadline</th>
  </tr>
<% Conference.with_open_submissions.each do |conf| %>
  <tr>
    <td><%= link_to conf.name, conf %></td>
    <td><%= conf.start_date %></td>
    <td><%= conf.end_date %></td>
    <td><%= submission_deadline_distance(conf) %></td>
  </tr>
<% end %>
</table>

app/views/conferences/new.html.erb
<% title 'New Conference' %>

<%= render 'form' %>

app/views/conferences/show.html.erb
<% title @conference.name %>

<table>
  <tr>
    <th>Start Date:</th>
    <td><%= @conference.start_date %></td>
  </tr>
  <tr>
    <th>End Date:</th>
    <td><%= @conference.end_date %></td>
  </tr>
  <tr>
    <th>Submission Deadline:</th>
    <td><%= @conference.submission_deadline %></td>
  </tr>
  <tr>
    <th>Point of Contact:</th>
    <td><%= mail_to @conference.poc.email %></td>
  </tr>
</table>

<table>
  <tr>
    <th>Submission Title</th>
    <th>Primary Author</th>
  </tr>
  
  <% @conference.submissions.each do |sub| %>
    <tr>
      <td><%= link_to sub.title, sub %></td>
      <td><%= link_to sub.authors.first.full_name, sub.authors.first %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "New Submission", new_conference_submission_url(@conference) if @conference.taking_submissions? %>
</p>

app/views/institutions/index.html.erb
<ul>
  <% @institutions.each do |insti| %>
    <li><%= link_to insti.name, insti %></li>
  <% end %>
  <li><%= link_to "Add another institution.", new_institution_url %></li>
</ul>

app/views/institutions/new.html.erb
<% title "New Institution" %>

<%= form_for(@institution) do |f| %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <%= f.submit %>
<% end %>

app/views/institutions/show.html.erb
<% title @institution.name %>

app/views/submissions/_form.html.erb
<%= form_for(@submission, :html => { :multipart => true }) do |f| %>

  <%= f.error_messages %>
  
  <div class="field">
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
      <%= f.hidden_field :conference_id, :value => params[:conference_id] %>
    </p>
  </div>
  
  <div class="field">
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
  </div>
  
  <div class="field">
    <p>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </p>
  </div>

  <%= f.submit %>
<% end %>

app/views/submissions/edit.html.erb
<%= render 'form' %>

app/views/submissions/index.html.erb
<% title "Submissions" %>


<ul>
  <% @submissions.each do |sub| %>
    <li><%= link_to sub.title, sub %></li>
  <% end %>
  <li><%= link_to "Create a new submission", new_submission_url(@user) %></li>
</ul>

app/views/submissions/new.html.erb
<% title "New Submission" %>

<%= render 'form' %>

app/views/submissions/show.html.erb
<% title @submission.title %>

<div id="status">
  Status: <%= @submission.state.humanize %>
  Conference: <%= @submission.conference.name %>
</div>

<ul>
  <% @submission.authors.each do |auth| %>
    <li><%= link_to auth.full_name, auth %></li>
  <% end %>
  <li class="no_pdf"><%= link_to "Add an author", new_submission_authorship_url(@submission) %></li>
</ul>

<%= @submission.body %><br />

<%= image_tag @submission.image.url(:publishable) unless @submission.image_file_name.nil? %>

<p id="pdf_link">
  <%= link_to "PDF Version", submission_url(@submission, :format => "pdf") %>
</p>

<% if @submission.pending_submission? %>
  <p>
    <%= button_to "Submit for approval", submit_submission_url(@submission), :method => :put, :class => :no_pdf %>
  </p>
<% end %>

app/views/users/show.html.erb
<% title @user.email %>

<ul>
  <% @user.submissions.each do |sub| %>
    <li><%= link_to sub.title, sub %></li>
  <% end %>
</ul>